### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by trockxi** [LuciferJack/mysqlis#1]
[root@test1 mysqlis]# sh sync_ab.sh 
Do you wish to copy table from 120.78.64.119 3306  to localhost 3306 ? (y or n)y
Please enter tablename as  input: 
endpoint_counter
You entered: endpoint_counter  
endpoint_counter

sync_ab.sh: line 37: copyTable: command not found
Do you wish to copy table from 120.78.64.119 3306  to localhost 3306 ? (y or n)

请问脚本37行要如何修改？

**Comment by LuciferJack** [comment]
是不是上面多了一个e，？ 把那个e去掉。然后copyTableIncre.sh在同一个目录里
![image](https://user-images.githubusercontent.com/10828459/32108537-9ab7beb8-bb64-11e7-8fe0-7f4180b04e71.png)

**Comment by trockxi** [comment]
e已经去掉了   是下面找不到copyTable

**Comment by LuciferJack** [comment]
现在可以了吗？假如不行，你的目录结构是什么？能否给我看看
或者你可以下载最新的看看。

**Comment by trockxi** [comment]
运行不通过
[root@test1 mysqlis]# pwd
/opt/scripts/mysqlis
[root@test1 mysqlis]# ll
total 16
-rwxr-xr-x 1 root root 2062 Oct 27 14:01 copyTableIncre.sh
drwxr-xr-x 2 root root 4096 Oct 27 14:10 log
-rw-r--r-- 1 root root  309 Oct 27 14:01 README.md
-rw-r--r-- 1 root root  991 Oct 27 14:33 sync_ab.sh
[root@test1 mysqlis]# sh copyTableIncre.sh 
[root@test1 mysqlis]# sh sync_ab.sh 
sync_ab.sh: line 37: syntax error near unexpected token `;;'
sync_ab.sh: line 37: `                copyTable();;'

**Comment by trockxi** [comment]
. copyTableIncre.sh 也需要改成  sh  copyTableIncre.sh 或 ./copyTableIncre.sh
不然报错
[root@test1 mysqlis]# sh sync_ab.sh 
sync_ab.sh: line 2: .: copyTableIncre.sh: file not found

**Comment by LuciferJack** [comment]
`sync_ab.sh: line 2: .: copyTableIncre.sh: file not found`
这个错误很明显，文件copyTableIncre.sh没有找到，是否在同**一个目录**下？
`sync_ab.sh: line 37: syntax error near unexpected token ;;' sync_ab.sh: line 37: copyTable();;'`
这个错误，说明你的bash不支持这个语法。
执行一下：
`which sh` 
出现什么？
是否你的 `/bin/bash` 是这样的？假如不是，对应的!#修改成你的。
` /bin/bash --version` 对应的版本多少？

**Comment by trockxi** [comment]
至于目录，可以看我ll的回显，确实在同一个目录
[root@test1 ~]# which sh
/bin/sh

[root@test1 ~]# /bin/bash --version
GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

[root@test1 ~]# cd /opt/scripts/mysqlis/
[root@test1 mysqlis]# ll
total 16
-rwxr-xr-x 1 root root 2062 Oct 27 14:01 copyTableIncre.sh
drwxr-xr-x 2 root root 4096 Oct 27 14:10 log
-rw-r--r-- 1 root root  309 Oct 27 14:01 README.md
-rw-r--r-- 1 root root  990 Nov  1 22:43 sync_ab.sh

[root@test1 mysqlis]# vim copyTableIncre.sh 
#!/bin/sh

[root@test1 mysqlis]# vim sync_ab.sh 
#!/bin/sh

[root@test1 mysqlis]# sh sync_ab.sh 
sync_ab.sh: line 37: syntax error near unexpected token `;;'
sync_ab.sh: line 37: `                copyTable();;'

不知在哪个系统版本下是成功的？

**Comment by LuciferJack** [comment]
版本没问题，我的比你的还低。
在gnu下面，`#!/bin/sh `默认都是用的bash。
你执行一下：`bash -n sync_ab.sh` 你那应该会报语法错误。那就真是语法错误了
你对脚本做修改了吗

**Comment by trockxi** [comment]
[root@test1 mysqlis]# bash -n sync_ab.sh
sync_ab.sh: line 37: syntax error near unexpected token `;;'
sync_ab.sh: line 37: `                copyTable();;'

没做什么修改，就前端服务器信息做了修改，后面的都没动，都是直接clone下来的

**Comment by trockxi** [comment]
重新copy了那一行，运行是通过了
但是提示下面的错误，找不到copyTable
[root@test1 mysqlis]# bash -n sync_ab.sh
[root@test1 mysqlis]# sh sync_ab.sh 
Do you wish to copy table from 120.78.64.129 3306  to localhost 3306 ? (y or n)y
Please enter tablename as  input: 
graph
You entered: graph  
graph

sync_ab.sh: line 37: copyTable: command not found
Do you wish to copy table from 120.78.64.129 3306  to localhost 3306 ? (y or n)y
Please enter tablename as  input: 
L1027
You entered: L1027  
L1027

sync_ab.sh: line 37: copyTable: command not found
Do you wish to copy table from 120.78.64.129 3306  to localhost 3306 ? (y or n)

**Comment by LuciferJack** [comment]
恩。那就进入正轨了。
在 **sync_ab.sh**文件的第二行
`source  copyTableIncre.sh 或者 .  copyTableIncre.sh`

**Comment by trockxi** [comment]
sync_ab.sh: line 37: copyTable: command not found

**Comment by LuciferJack** [comment]
执行：
` bash  -v sync_ab.sh `
的完整输出给我一份哈

**Comment by trockxi** [comment]
[root@test1 mysqlis]# bash -v sync_ab.sh
#!/bin/sh
./copyTableIncre.sh

# The following database will be DELETED first:
STATUS=''

HOST='120.78.64.129'
PORT=3306
COPY_DB=graph
COPY_TABLE=$COPY_USE
USER=root
PASS="xxxx"
ERROR=/opt/scripts/mysqlis/log/duplicate_mysql_error.log
OPT=" --single-transaction  "

LOCAL_HOST='localhost'
LOCAL_DB=L1027
LOCAL_PORT=3306
LOCAL_TABLE=$COPY_USE
LOCAL_USER=root
LOCAL_PASS="xxxx"


WHERE_COND=''
COPY_USE=''

while true; do
        read -p "Do you wish to copy table from $HOST $PORT  to $LOCAL_HOST $LOCAL_PORT ? (y or n)" yn
    case $yn in
        [Yy]* )echo "Please enter tablename as  input: ";
                read input_variable where_input;
                echo "You entered: $input_variable  $where_input";
                COPY_USE=$input_variable;
                WHERE_COND=$where_input;
                echo $COPY_USE;
                echo $WHERE_COND;
                copyTable;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
Do you wish to copy table from 120.78.64.129 3306  to localhost 3306 ? (y or n)y
Please enter tablename as  input: 
graph
You entered: graph  
graph

sync_ab.sh: line 37: copyTable: command not found
Do you wish to copy table from 120.78.64.129 3306  to localhost 3306 ? (y or n)

**Comment by LuciferJack** [comment]
`./copyTableIncre.sh`
修改成：
`source copyTableIncre.sh`
